Repository python-microservices/pyms, pull requests merged in 2020-10, with the labels that each got.

#174 Config reload endpoint
  pyms/flask/app/create_app.py
  pyms/flask/configreload/__init__.py
  pyms/flask/configreload/configreload.py
  pyms/flask/healthcheck/healthcheck.py
  tests/config-tests-reload1.yml
  tests/config-tests-reload2.yml
  tests/test_flask.py
Labels: hacktoberfest-accepted

#191 Feature/089 namespace on env vars with backward compatibility
  docs/configuration.md
  docs/encrypt_decryt_configuration.md
  docs/ms_class.md
  examples/mininum_microservice_docker/Dockerfile
  pylintrc
  pyms/cmd/main.py
  pyms/config/conf.py
  pyms/config/confile.py
  pyms/constants.py
  pyms/crypt/fernet.py
  pyms/flask/app/create_app.py
  pyms/utils/utils.py
  tests/config-tests-debug-off.yml
  tests/config-tests-debug.yml
  tests/config-tests-deprecated.yml
  tests/test_cmd.py
  tests/test_config.py
  tests/test_crypt.py
Labels: Hacktoberfest, hacktoberfest-accepted

#202 Fix reload endpoint and Added docs to use this endpoint
  docs/configuration.md
  pyms/utils/files.py
Labels: bug, documentation
